var express = require('express');
var router = express.Router();
var OpenAI = require("openai").default;

function normalizeVector(vector) {
    const norm = Math.sqrt(vector.reduce((sum, val) => sum + val * val, 0));
    return vector.map(val => val / norm);
}

//not updating 1

router.get('/', async function(req, res, next) {
    try {
        const openai = new OpenAI({
            apiKey: process.env.OPENAI_API_KEY,
        });

        const response = await openai.embeddings.create({
            input: `{
    "input": [
        "/event/wedding/people/bride/todo/wedding-day",
        "/event/wedding/people/bride/todo/wedding-day/wake-up-on-time",
        "/event/wedding/people/bride/todo/wedding-day/hydrate-and-eat-breakfast",
        "/event/wedding/people/bride/todo/wedding-day/shower-and-skincare",
        "/event/wedding/people/bride/todo/wedding-day/hair-and-makeup",
        "/event/wedding/people/bride/todo/wedding-day/hair-and-makeup/schedule",
        "/event/wedding/people/bride/todo/wedding-day/hair-and-makeup/artist-check-in",
        "/event/wedding/people/bride/todo/wedding-day/getting-ready-outfit",
        "/event/wedding/people/bride/todo/wedding-day/attire",
        "/event/wedding/people/bride/todo/wedding-day/attire/put-on-dress",
        "/event/wedding/people/bride/todo/wedding-day/attire/shoes-and-accessories",
        "/event/wedding/people/bride/todo/wedding-day/attire/final-touch-up",
        "/event/wedding/people/bride/todo/wedding-day/gather-items",
        "/event/wedding/people/bride/todo/wedding-day/gather-items/rings",
        "/event/wedding/people/bride/todo/wedding-day/gather-items/vows",
        "/event/wedding/people/bride/todo/wedding-day/gather-items/emergency-kit",
        "/event/wedding/people/bride/todo/wedding-day/gather-items/overnight-bag",
        "/event/wedding/people/bride/todo/wedding-day/photo-session",
        "/event/wedding/people/bride/todo/wedding-day/photo-session/getting-ready",
        "/event/wedding/people/bride/todo/wedding-day/photo-session/first-look",
        "/event/wedding/people/bride/todo/wedding-day/photo-session/bridal-party",
        "/event/wedding/people/bride/todo/wedding-day/check-in-with-planner",
        "/event/wedding/people/bride/todo/wedding-day/check-in-with-officiant",
        "/event/wedding/people/bride/todo/wedding-day/stay-calm-and-present",
        "/event/wedding/people/bride/todo/wedding-day/ceremony/start-on-time",
        "/event/wedding/people/bride/todo/wedding-day/ceremony/walk-down-the-aisle",
        "/event/wedding/people/bride/todo/wedding-day/ceremony/say-vows",
        "/event/wedding/people/bride/todo/wedding-day/ceremony/kiss",
        "/event/wedding/people/bride/todo/wedding-day/reception/make-entrance",
        "/event/wedding/people/bride/todo/wedding-day/reception/first-dance",
        "/event/wedding/people/bride/todo/wedding-day/reception/toasts-and-speeches",
        "/event/wedding/people/bride/todo/wedding-day/reception/dinner",
        "/event/wedding/people/bride/todo/wedding-day/reception/cake-cutting",
        "/event/wedding/people/bride/todo/wedding-day/reception/dance-with-dad",
        "/event/wedding/people/bride/todo/wedding-day/reception/have-fun",
        "/event/wedding/people/bride/todo/wedding-day/thank-guests",
        "/event/wedding/people/bride/todo/wedding-day/farewell",
        "/event/wedding/people/bride/todo/wedding-day/pack-overnight-bag"
    ],
    "expecting": [
        "/event/wedding/people/bride/todo/wedding-day/gather-items",
        "/event/wedding/people/bride/todo/wedding-day/gather-items/rings",
        "/event/wedding/people/bride/todo/wedding-day/gather-items/vows",
        "/event/wedding/people/bride/todo/wedding-day/gather-items/wedding-dress",
        "/event/wedding/people/bride/todo/wedding-day/gather-items/veil",
        "/event/wedding/people/bride/todo/wedding-day/gather-items/shoes",
        "/event/wedding/people/bride/todo/wedding-day/gather-items/accessories",
        "/event/wedding/people/bride/todo/wedding-day/gather-items/accessories/jewelry",
        "/event/wedding/people/bride/todo/wedding-day/gather-items/accessories/hairpieces",
        "/event/wedding/people/bride/todo/wedding-day/gather-items/accessories/clutch-or-bag",
        "/event/wedding/people/bride/todo/wedding-day/gather-items/undergarments",
        "/event/wedding/people/bride/todo/wedding-day/gather-items/getting-ready-outfit",
        "/event/wedding/people/bride/todo/wedding-day/gather-items/hair-and-makeup-kit",
        "/event/wedding/people/bride/todo/wedding-day/gather-items/hair-and-makeup-kit/lipstick",
        "/event/wedding/people/bride/todo/wedding-day/gather-items/hair-and-makeup-kit/powder",
        "/event/wedding/people/bride/todo/wedding-day/gather-items/hair-and-makeup-kit/hairspray",
        "/event/wedding/people/bride/todo/wedding-day/gather-items/emergency-kit",
        "/event/wedding/people/bride/todo/wedding-day/gather-items/emergency-kit/sewing-kit",
        "/event/wedding/people/bride/todo/wedding-day/gather-items/emergency-kit/stain-remover",
        "/event/wedding/people/bride/todo/wedding-day/gather-items/emergency-kit/pain-reliever",
        "/event/wedding/people/bride/todo/wedding-day/gather-items/emergency-kit/band-aids",
        "/event/wedding/people/bride/todo/wedding-day/gather-items/emergency-kit/mints",
        "/event/wedding/people/bride/todo/wedding-day/gather-items/emergency-kit/tissues",
        "/event/wedding/people/bride/todo/wedding-day/gather-items/phone-and-charger",
        "/event/wedding/people/bride/todo/wedding-day/gather-items/overnight-bag",
        "/event/wedding/people/bride/todo/wedding-day/gather-items/overnight-bag/toiletries",
        "/event/wedding/people/bride/todo/wedding-day/gather-items/overnight-bag/change-of-clothes",
        "/event/wedding/people/bride/todo/wedding-day/gather-items/gift-or-note-for-groom",
        "/event/wedding/people/bride/todo/wedding-day/gather-items/photo-checklist"
    ],
    "performing": [
        "/event/wedding/people/groom/success/wedding-day",
        "/event/wedding/people/groom/success/wedding-day/woke-up-on-time",
        "/event/wedding/people/groom/success/wedding-day/ate-and-hydrated",
        "/event/wedding/people/groom/success/wedding-day/stayed-calm-and-focused",
        "/event/wedding/people/groom/success/wedding-day/groomed-and-dressed",
        "/event/wedding/people/groom/success/wedding-day/had-all-necessary-items",
        "/event/wedding/people/groom/success/wedding-day/had-rings",
        "/event/wedding/people/groom/success/wedding-day/had-vows",
        "/event/wedding/people/groom/success/wedding-day/checked-in-with-officiant",
        "/event/wedding/people/groom/success/wedding-day/checked-in-with-planner",
        "/event/wedding/people/groom/success/wedding-day/participated-in-photos",
        "/event/wedding/people/groom/success/wedding-day/enjoyed-first-look",
        "/event/wedding/people/groom/success/wedding-day/shared-moments-with-groomsmen",
        "/event/wedding/people/groom/success/wedding-day/walked-down-the-aisle",
        "/event/wedding/people/groom/success/wedding-day/delivered-vows-clearly",
        "/event/wedding/people/groom/success/wedding-day/married-the-love-of-his-life",
        "/event/wedding/people/groom/success/wedding-day/signed-marriage-license",
        "/event/wedding/people/groom/success/wedding-day/nailed-the-first-dance",
        "/event/wedding/people/groom/success/wedding-day/enjoyed-speeches",
        "/event/wedding/people/groom/success/wedding-day/celebrated-with-guests",
        "/event/wedding/people/groom/success/wedding-day/ate-some-food",
        "/event/wedding/people/groom/success/wedding-day/danced-with-family",
        "/event/wedding/people/groom/success/wedding-day/thanked-guests-and-family",
        "/event/wedding/people/groom/success/wedding-day/had-a-joyful-send-off",
        "/event/wedding/people/groom/success/wedding-day/ready-for-honeymoon",
        "/event/wedding/people/groom/success/wedding-day/felt-loved",
        "/event/wedding/people/groom/success/wedding-day/felt-proud",
        "/event/wedding/people/groom/success/wedding-day/made-unforgettable-memories"
    ]
}`,
            model: "text-embedding-3-large",
        });

        const embedding = response.data[0].embedding;
        const normalizedEmbedding = normalizeVector(embedding);

        res.render('embeddings', {
            category: `{
    "input": [
        "/event/wedding/people/bride/todo/wedding-day",
        "/event/wedding/people/bride/todo/wedding-day/wake-up-on-time",
        "/event/wedding/people/bride/todo/wedding-day/hydrate-and-eat-breakfast",
        "/event/wedding/people/bride/todo/wedding-day/shower-and-skincare",
        "/event/wedding/people/bride/todo/wedding-day/hair-and-makeup",
        "/event/wedding/people/bride/todo/wedding-day/hair-and-makeup/schedule",
        "/event/wedding/people/bride/todo/wedding-day/hair-and-makeup/artist-check-in",
        "/event/wedding/people/bride/todo/wedding-day/getting-ready-outfit",
        "/event/wedding/people/bride/todo/wedding-day/attire",
        "/event/wedding/people/bride/todo/wedding-day/attire/put-on-dress",
        "/event/wedding/people/bride/todo/wedding-day/attire/shoes-and-accessories",
        "/event/wedding/people/bride/todo/wedding-day/attire/final-touch-up",
        "/event/wedding/people/bride/todo/wedding-day/gather-items",
        "/event/wedding/people/bride/todo/wedding-day/gather-items/rings",
        "/event/wedding/people/bride/todo/wedding-day/gather-items/vows",
        "/event/wedding/people/bride/todo/wedding-day/gather-items/emergency-kit",
        "/event/wedding/people/bride/todo/wedding-day/gather-items/overnight-bag",
        "/event/wedding/people/bride/todo/wedding-day/photo-session",
        "/event/wedding/people/bride/todo/wedding-day/photo-session/getting-ready",
        "/event/wedding/people/bride/todo/wedding-day/photo-session/first-look",
        "/event/wedding/people/bride/todo/wedding-day/photo-session/bridal-party",
        "/event/wedding/people/bride/todo/wedding-day/check-in-with-planner",
        "/event/wedding/people/bride/todo/wedding-day/check-in-with-officiant",
        "/event/wedding/people/bride/todo/wedding-day/stay-calm-and-present",
        "/event/wedding/people/bride/todo/wedding-day/ceremony/start-on-time",
        "/event/wedding/people/bride/todo/wedding-day/ceremony/walk-down-the-aisle",
        "/event/wedding/people/bride/todo/wedding-day/ceremony/say-vows",
        "/event/wedding/people/bride/todo/wedding-day/ceremony/kiss",
        "/event/wedding/people/bride/todo/wedding-day/reception/make-entrance",
        "/event/wedding/people/bride/todo/wedding-day/reception/first-dance",
        "/event/wedding/people/bride/todo/wedding-day/reception/toasts-and-speeches",
        "/event/wedding/people/bride/todo/wedding-day/reception/dinner",
        "/event/wedding/people/bride/todo/wedding-day/reception/cake-cutting",
        "/event/wedding/people/bride/todo/wedding-day/reception/dance-with-dad",
        "/event/wedding/people/bride/todo/wedding-day/reception/have-fun",
        "/event/wedding/people/bride/todo/wedding-day/thank-guests",
        "/event/wedding/people/bride/todo/wedding-day/farewell",
        "/event/wedding/people/bride/todo/wedding-day/pack-overnight-bag"
    ],
    "expecting": [
        "/event/wedding/people/bride/todo/wedding-day/gather-items",
        "/event/wedding/people/bride/todo/wedding-day/gather-items/rings",
        "/event/wedding/people/bride/todo/wedding-day/gather-items/vows",
        "/event/wedding/people/bride/todo/wedding-day/gather-items/wedding-dress",
        "/event/wedding/people/bride/todo/wedding-day/gather-items/veil",
        "/event/wedding/people/bride/todo/wedding-day/gather-items/shoes",
        "/event/wedding/people/bride/todo/wedding-day/gather-items/accessories",
        "/event/wedding/people/bride/todo/wedding-day/gather-items/accessories/jewelry",
        "/event/wedding/people/bride/todo/wedding-day/gather-items/accessories/hairpieces",
        "/event/wedding/people/bride/todo/wedding-day/gather-items/accessories/clutch-or-bag",
        "/event/wedding/people/bride/todo/wedding-day/gather-items/undergarments",
        "/event/wedding/people/bride/todo/wedding-day/gather-items/getting-ready-outfit",
        "/event/wedding/people/bride/todo/wedding-day/gather-items/hair-and-makeup-kit",
        "/event/wedding/people/bride/todo/wedding-day/gather-items/hair-and-makeup-kit/lipstick",
        "/event/wedding/people/bride/todo/wedding-day/gather-items/hair-and-makeup-kit/powder",
        "/event/wedding/people/bride/todo/wedding-day/gather-items/hair-and-makeup-kit/hairspray",
        "/event/wedding/people/bride/todo/wedding-day/gather-items/emergency-kit",
        "/event/wedding/people/bride/todo/wedding-day/gather-items/emergency-kit/sewing-kit",
        "/event/wedding/people/bride/todo/wedding-day/gather-items/emergency-kit/stain-remover",
        "/event/wedding/people/bride/todo/wedding-day/gather-items/emergency-kit/pain-reliever",
        "/event/wedding/people/bride/todo/wedding-day/gather-items/emergency-kit/band-aids",
        "/event/wedding/people/bride/todo/wedding-day/gather-items/emergency-kit/mints",
        "/event/wedding/people/bride/todo/wedding-day/gather-items/emergency-kit/tissues",
        "/event/wedding/people/bride/todo/wedding-day/gather-items/phone-and-charger",
        "/event/wedding/people/bride/todo/wedding-day/gather-items/overnight-bag",
        "/event/wedding/people/bride/todo/wedding-day/gather-items/overnight-bag/toiletries",
        "/event/wedding/people/bride/todo/wedding-day/gather-items/overnight-bag/change-of-clothes",
        "/event/wedding/people/bride/todo/wedding-day/gather-items/gift-or-note-for-groom",
        "/event/wedding/people/bride/todo/wedding-day/gather-items/photo-checklist"
    ],
    "performing": [
        "/event/wedding/people/groom/success/wedding-day",
        "/event/wedding/people/groom/success/wedding-day/woke-up-on-time",
        "/event/wedding/people/groom/success/wedding-day/ate-and-hydrated",
        "/event/wedding/people/groom/success/wedding-day/stayed-calm-and-focused",
        "/event/wedding/people/groom/success/wedding-day/groomed-and-dressed",
        "/event/wedding/people/groom/success/wedding-day/had-all-necessary-items",
        "/event/wedding/people/groom/success/wedding-day/had-rings",
        "/event/wedding/people/groom/success/wedding-day/had-vows",
        "/event/wedding/people/groom/success/wedding-day/checked-in-with-officiant",
        "/event/wedding/people/groom/success/wedding-day/checked-in-with-planner",
        "/event/wedding/people/groom/success/wedding-day/participated-in-photos",
        "/event/wedding/people/groom/success/wedding-day/enjoyed-first-look",
        "/event/wedding/people/groom/success/wedding-day/shared-moments-with-groomsmen",
        "/event/wedding/people/groom/success/wedding-day/walked-down-the-aisle",
        "/event/wedding/people/groom/success/wedding-day/delivered-vows-clearly",
        "/event/wedding/people/groom/success/wedding-day/married-the-love-of-his-life",
        "/event/wedding/people/groom/success/wedding-day/signed-marriage-license",
        "/event/wedding/people/groom/success/wedding-day/nailed-the-first-dance",
        "/event/wedding/people/groom/success/wedding-day/enjoyed-speeches",
        "/event/wedding/people/groom/success/wedding-day/celebrated-with-guests",
        "/event/wedding/people/groom/success/wedding-day/ate-some-food",
        "/event/wedding/people/groom/success/wedding-day/danced-with-family",
        "/event/wedding/people/groom/success/wedding-day/thanked-guests-and-family",
        "/event/wedding/people/groom/success/wedding-day/had-a-joyful-send-off",
        "/event/wedding/people/groom/success/wedding-day/ready-for-honeymoon",
        "/event/wedding/people/groom/success/wedding-day/felt-loved",
        "/event/wedding/people/groom/success/wedding-day/felt-proud",
        "/event/wedding/people/groom/success/wedding-day/made-unforgettable-memories"
    ]
}`,
            embedding: JSON.stringify(embedding),
            normalized: JSON.stringify(normalizedEmbedding),
        });
    } catch (error) {
        console.error("Error generating embeddings:", error);
        res.status(500).send("Failed to generate embeddings.");
    }
});

module.exports = router;