name: Install NPM Package

on:
  repository_dispatch:
    types: [install-npm-package]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.MY_GITHUB_PAT }}

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install npm package
      run: |
        cd app
        npm install --save ${{ github.event.client_payload.packageName }}

    - name: Zip node_modules
      run: |
        cd app/node_modules
        for dir in */; do
          zip -r "${dir%/}.zip" "$dir"
        done

    - name: Upload Zipped Modules to S3
      run: |
        cd app/node_modules
        for zipFile in *.zip; do
          aws s3 cp "$zipFile" "s3://${{ secrets.AWS_S3_BUCKET }}/node_modules/$zipFile"
        done
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'us-east-1'

    - name: Commit and Push Changes
      run: |
        git config --global user.name 'Lambda_Github'
        git config --global user.email 'jaustinhughes@outlook.com'
        git add app/package.json app/package-lock.json
        git commit -m "Install ${{ github.event.client_payload.packageName }} npm package" || echo "No changes to commit"
        git push
