name: Install NPM Package

on:
  repository_dispatch:
    types: [install-npm-package]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # Specify the Node.js version

    - name: Install npm package
      run: npm install passport-apple

    - name: Commit and Push Changes
      run: |
        git config --global user.name 'Lambda_Github'
        git config --global user.email 'jaustinhughes@outlook.com'
        git add package.json package-lock.json
        git commit -m "Install passport-apple npm package"
        git push