name: Install NPM Package

on:
  repository_dispatch:
    types: [install-npm-package]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.MY_GITHUB_PAT }}

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Capture pre-install state of node_modules
      run: |
        cd app
        if [ ! -d "node_modules" ]; then
          mkdir -p node_modules
          touch pre_install.txt
        else
          ls app/node_modules > pre_install.txt
        fi

    - name: Install npm package
      run: |
        cd app
        npm install --save ${{ github.event.client_payload.packageName }}

    - name: Capture post-install state of node_modules
      run: |
        cd app
        ls node_modules > post_install.txt

    - name: Zip and upload new modules
      run: |
        cd app/node_modules
        aws s3 cp ../post_install.txt s3://${{ secrets.AWS_S3_BUCKET }}/new_modules.zip

    - name: Commit and Push Changes
      run: |
        git config --global user.name 'Lambda_Github'
        git config --global user.email 'jaustinhughes@outlook.com'
        git add app/package.json app/package-lock.json
        git commit -m "Install ${{ github.event.client_payload.packageName }} npm package" || echo "No changes to commit"
        git push

    - name: Upload to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-west-1' # change to your region
        SOURCE_DIR: 'app'

    - name: Cleanup
      run: |
        cd app
        rm pre_install.txt post_install.txt new_modules.zip